# Generated by Django 4.0.2 on 2022-03-30 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mob', models.CharField(max_length=20, unique=True)),
                ('Address', models.CharField(max_length=300)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mob', models.CharField(max_length=20, unique=True)),
                ('Address', models.CharField(max_length=300)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('work', models.CharField(max_length=100)),
                ('charges', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Appointment_date', models.CharField(max_length=300)),
                ('completed', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.users')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.workers')),
            ],
        ),
    ]
